name: Fast Build APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 3. Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 4. Install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: 5. Build APK locally on Github Server
        run: eas build -p android --profile preview --local --non-interactive --output=app-release.apk

      - name: 6. Upload APK for Download
        uses: actions/upload-artifact@v4
        with:
          name: app-preview-apk
          path: app-release.apk
